### ISSUE TITLE
Missing .gcloudignore file

### ISSUE THREAD

**Issue by ZakSingh** [arjunyel/firestore-apollo-graphql#1]
The docs refers to a .gcloudignore file which does not exist in the repo.

**Comment by codediodeio** [comment]
The .gcloudignore file should be automatically generated when your run `gcloud app deploy` for the first time, so you don't actually need to create it.

**Comment by arjunyel** [comment]
@ZakSingh I uploaded a gcloudignore that manually targeted the extra stuff but the regular .gcloudignore should also work fine
