### ISSUE TITLE
No .gcloudignore in repo as mentioned at bottom of README

### ISSUE THREAD

**Issue by gabriel-wilkes** [arjunyel/firestore-apollo-graphql#2]
I see that a .gcloudignore file is generated when I deploy to gcloud but I thought that perhaps the default one isn't the best. Can you add your .gcloudignore file to the repo as you mention it at the bottom of the README? Thanks

**Comment by arjunyel** [comment]
Sorry about that, when I uploaded this to github it for some reason left it out. Ill get it in ASAP

**Comment by arjunyel** [comment]
Should be fixed, let me know if you have any problems or questions!

**Comment by gabriel-wilkes** [comment]
Thanks, your update to grab the port from the environment variables also got me working on App Engine.

**Comment by arjunyel** [comment]
Yeah I'm honestly confused how it ever worked on app engine for me before that, I wonder if just by chance I was assigned the 4000 port 😂
