### ISSUE TITLE
Example of using mutations

### ISSUE THREAD

**Issue by drejohnson** [arjunyel/firestore-apollo-graphql#4]
Any plans to add examples of using mutations to add users and tweets?

**Comment by arjunyel** [comment]
@drejohnson Hello thanks for checking out my repo :D In the second tutorial I made an example of a mutation with an Angular frontend, does that help?

https://youtu.be/Wc7bJ2uv694

https://github.com/arjunyel/angular-apollo-example

**Comment by drejohnson** [comment]
Oh cool, and yeah that's perfect. Thanks
